"""added user public_id

Revision ID: 8f34c7f76696
Revises: 8160b6521bff
Create Date: 2019-09-06 13:40:25.612661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f34c7f76696'
down_revision = '8160b6521bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'User', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'public_id')
    # ### end Alembic commands ###
